### ISSUE TITLE
Stop putting .history folder in working folder

### ISSUE THREAD

**Issue by robross0606** [zabel-xyz/local-history#110]
Putting the .history folder in your working folder by default is a terrible idea. It causes indexing problems in VSCode. It causes problems with Jest, git and who knows what else. Put the folder someplace else by default like the user's tmp folder.  I know you have a means to specify a fixed path, but this is very tedious if you juggle multiple projects.  Find another spot to automatically place the .history data.

**Comment by leocaseiro** [comment]
You change your settings for **Local-history: Path** (search in vscode preferences).

In my case I added inside `.vscode/history`, eg:
`${workspaceFolder}/.vscode/history/`

![Screen Shot 2020-06-09 at 1 03 19 pm](https://user-images.githubusercontent.com/940070/84101585-a2493100-aa51-11ea-8f85-41650e2116eb.png)



You can change your **path** and add the file to **.gitignore**.
.gitignore:
`.vscode/history/*`

Here are some useful VS Code Variables if you don't want it inside `.vscode`
https://code.visualstudio.com/docs/editor/variables-reference

**Comment by robross0606** [comment]
Good idea, but doesn't change the ticket.  This shouldn't be the default behavior.

**Comment by zabel-xyz** [comment]
VSCode variables are not supported. Only ${workspaceFolder}, see [doc](https://github.com/zabel-xyz/local-history/blob/master/README.md)
I don't want to change default value. This is like that since several year without problem. I don't want to change user's settings (change default value = change user settings).
You can change it in your user settings if you want.
