### ISSUE TITLE
Change .history folder into .vscode folder

### ISSUE THREAD

**Issue by robsonrosa** [zabel-xyz/local-history#26]
I really don't know if it's possible, but it would be great if the `.history` folder was moved into `.vscode` folder. It's annoying changing all my `.gitignore` files in several projects just to add an extension.

**Comment by zabel-xyz** [comment]
I'll add a variable ${workspaceFolder}, so you can use it in settings 
`local-history.path: ${workspaceFolder}\.vscode`

**Comment by marmaak** [comment]
> I'll add a variable ${workspaceFolder}, so you can use it in settings
local-history.path: ${workspaceFolder}\.vscode

Does it work also with the new multiroot workspace? Because I am not able to make it work with the last version of VSCode (1.18)

With the following multiroot structure:

```
--+
  | -- Configuration
  | -- A
  | -- B
  | -- C
```

I wish to save the history of the folders _A_, _B_ and _C_ into the _Configuration/.history_ folder

I tried a lot of combinations for the `local-history.path` but none of them work for me.

Can you give me some feedback? Thanks

**Comment by robsonrosa** [comment]
Have you tried using the absolute path for _Configuration_ folder?

**Comment by zabel-xyz** [comment]
@marmaak 

> I wish to save the history of the folders A, B and C into the Configuration/.history folder

To do this, configure your file ???.code-workspace like that:
```
{
	"folders": [
		{
			"path": "D:\\Develop\\_GIT\\develop"
		},
		{
			"path": "D:\\Develop\\_GIT\\develop\\db"
		},
		{
			"path": "D:\\Develop\\_GIT\\develop\\server"
		}
	],
	"settings": {
		"local-history.path": "D:\\Develop\\_GIT\\develop"
	}
}
```
Here I have 3 folders and the history is only in the first one.
So **D:\Develop\_GIT\develop\\.history\db** and **D:\Develop\_GIT\develop\\.history\server** 

Is that what you want ? If not, give me more details...

**Comment by marmaak** [comment]
Hi guys,

first of all, thanks for answers!

Well, the absolute path in the `local-history.path` setting works fine, but why I have to specify the absolute path instead of a relative one? All the `folders` in my settings file has a relative path, probably related to the workspace file that you mentioned (`???.code-workspace`) and in this way VSCode can compose the absolute paths, right?

The relative path can be useful if you are going to share your worksapce settings with other team mates for example.

Cheers

**Comment by zabel-xyz** [comment]
fix in version 1.6.2
${workspaceFolder}\.vscode => to have .history in .vscode folder
${workspaceFolder: 0} => to save always in first workspaceFolder (for multi-root)

**Comment by robsonrosa** [comment]
Works like a charm!! Thanks a lot!

**Comment by romanr** [comment]
why this is not set as a default in configuration?
