### ISSUE TITLE
VSCode codelense finds references in the .history folder

### ISSUE THREAD

**Issue by madmidi** [zabel-xyz/local-history#43]
Is it just my fault ?
Why nobody here and in the whole internet is reporting those issues ?
My VSCode codelense searches for references in the .history folder if it's in the workspace folder.
Therefor it finds 1000+ wrong references in the history files and that disables or crashes codelense and intellisense very often.
I've excluded the .histroy path in 'files.exclude' and 'search.exclude' but VSCode still ignores it.
The only workaround I've found is to move the .history folder outside the workspace folder using 'local-history.path'.
Because VSCode is still unable to exclude paths for reference search, you should think about a workaround in your app, e.g. :
You could add an underscore to every history file to change its extension and makes it an unknown file type for the codelense and maybe extensions, which searches files in the workspace folder, too.
When the user wants to open a history file in the editor, then you have to copy the history file to the windows temp folder, remove the underscore from the extension and open the temp file in the editor...

**Comment by kentcdodds** [comment]
Hi @zabel-xyz! First off, thanks for the extension! It's bringing me a lot of peace of mind :)

I'm having a similar issue where the jest testing framework (as configured by default and in create-react-app) will find all `.history` copies of test files and attempt to run them which is quite problematic. As it's a CLI tool irrespective of any code editor, it cannot take into account editor settings such as `search.exclude`.

I attempted to set `local-history.path` to: `~/.vscode-history/${workspaceFolder}` but got an error:

> ${workspaceFolder} must starts setting local-history.path ~/.vscode-history/${workspaceFolder}

<img width="472" alt="screen shot 2018-06-09 at 9 05 33 pm" src="https://user-images.githubusercontent.com/1500684/41197909-de3df2cc-6c28-11e8-931f-ae80805698a3.png">

What I really would like is if it were possible to configure the history to be stored in a dotfolder in my home directory.

For now, I'll configure it to be in the `node_modules` directory of my project: `${workspaceFolder}/node_modules/.history` But this is suboptimal because normally the `node_modules` directory is shorter-lived than the project itself so I'll likely lose saved copies of things overtime.

Thanks again!

**Comment by zabel-xyz** [comment]
Hello @kentcdodds,
Normally, you simply configure like this:
```
    local-history.path: ~/.vscode-history
```
But atfter some tests, it appears that **it doesn't work on linux**. (I developed this extension on Windows system).

I tried with this config: ```local-history.path: /home/myuser/.vscode-history```
for `~/develop/project1` the history will be save in `~/.vscode-history/.history/project1`

or with `local-history.absolute: true`
for `~/develop/project1` the history will be save in `~/.vscode-history/.history/home/myuser/develop/project1`
=> remove home/myuser ?

Here a bug: consider character ~ on linux system

**Comment by kentcdodds** [comment]
Awesome! That's good enough for me. Thank you!
