### ISSUE TITLE
Timeout when copyFile

### ISSUE THREAD

**Issue by hrvoj3e** [zabel-xyz/local-history#68]
Does this mean that a backup file has not been created in .history?
Is this timeout configurable?

> Timeout when copyFile: ' /home/username/code/sshfs/some/remote/path/Core.php => /home/username/app/code/local-history/.history/home/username/code/sshfs/some/remote/path/Core_20181203152821.php

https://github.com/zabel-xyz/local-history/blob/57c988460481e5122be59bdadbdaffb1aa4b01e5/src/history.controller.ts#L538

Hm... also I see in the .history dir that a new file has been created with today's timestamp but "Timeout when copyFile" is shown with an older timestamp.
Is this a backup before current changes.

My settings:
```
    "local-history.path": "/home/username/app/code/local-history",
    "local-history.absolute" : true,
    "local-history.daysLimit": 0,
    "local-history.saveDelay": 4,
    "local-history.dateLocale": "en-GB",
```
I am using SSHFS mounted dir on this project.

**Comment by zabel-xyz** [comment]
Hello,

There are 2 events:
1. **onWillSaveTextDocument** (before saving)
   "According to vscode: The current thresholds are 1.5 seconds as overall time budget
    and a listener can misbehave 3 times before being ignored." [(see api)](https://code.visualstudio.com/api/references/vscode-api)
   => Here I save the first version (original file). 
      This is done only the first time, when no other versions exists. and the timestamp is ~1 sec older.
2. **onSaveDocument** (after saving)
   This is done every time (or according to `settings.saveDelay`)

So, I think you have lost the first version (original) ? 

There is no settings for vscode timeout. I don't know how to improve this...

**Comment by nickpapoutsis** [comment]
I, too, started getting the same "Timeout when copyFile" error probably a month or so ago.

I started noticing random debug.log files all over and inside they had, usually, 1-2 lines of this:

`[0823/023744.477:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[0823/023744.524:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)`

I use Windows 10 64bit and VSC Insiders and I keep both up to date so it could be related to some update I installed but there's no way of knowing since I don't know when it all started (at first I only noticed he debug.log files, not the timeout errors).
