### ISSUE TITLE
doesnt work at all in ubuntu

### ISSUE THREAD

**Issue by erikdemarco** [zabel-xyz/local-history#73]
fresh install vscode
fresh install local history
open file, click save (nothing show in the 'local history' explorer panel)
click save 100x still nothing shows

**Comment by zabel-xyz** [comment]
I need more details:
What exactly is your system (version, ...) ? 
What do you open ? only a file,  a folder, a multi-root-workspace ?
What settings do you use for local-history ?

**Comment by erikdemarco** [comment]
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-18-generic snap

**Comment by erikdemarco** [comment]
What do you open ? only a file, a folder, a multi-root-workspace ?
only file.

What settings do you use for local-history ?
default setting (no change)

**Comment by zabel-xyz** [comment]
The default settings is to save in workspaceFolder\\.history.
If you open just a single file or a file not in workspaceFolder, and don't specify any`"local-history.path"` in your settings
=> This extension will not save anything, because there is no location defined to do that !

So open the workspaceFolder or define in your user settings `local-history.path`.
