### ISSUE TITLE
Local history does not work

### ISSUE THREAD

**Issue by lishine** [zabel-xyz/local-history#84]
The most up to date Vscode.
With no special settings set.
Not seeing the tab in the explorer and no .history folder

**Comment by zabel-xyz** [comment]
It works fine...

Not seeing the tab in the explorer ? See #23 
What platform ?

**Comment by lishine** [comment]
Yes, not seeing the tab.
That issue does not seem to help understand the problem.
It is windows

**Comment by zabel-xyz** [comment]
Sorry the true link is #34.
By default it's appear in explorer.
Use setting `local-history.treeLocation` if you want a dedicated tab.

Are you opening a folder or a single file ?

The default settings is to save in workspaceFolder\.history.
If you open just a single file or a file not in workspaceFolder, and don't specify any"local-history.path" in your settings
=> This extension will not save anything, because there is no location defined to do that !

So open the workspaceFolder or define in your user settings local-history.path.
